// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4RvmQdusyKNPKWAU_m9GnCdm87kTf4FU',
    appId: '1:778064361074:web:3835c12c296b91811eb4eb',
    messagingSenderId: '778064361074',
    projectId: 'telegram-e5aa0',
    authDomain: 'telegram-e5aa0.firebaseapp.com',
    storageBucket: 'telegram-e5aa0.firebasestorage.app',
    measurementId: 'G-XTSNPPP4J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXnAoMjcFYSBHK2ftymq_GDY3qDq3L2lY',
    appId: '1:778064361074:android:a7acee57c375365e1eb4eb',
    messagingSenderId: '778064361074',
    projectId: 'telegram-e5aa0',
    storageBucket: 'telegram-e5aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Az0iInDOJ_amEGAaQVHo-tuUCfplbBc',
    appId: '1:778064361074:ios:687cdc2eadcd3edd1eb4eb',
    messagingSenderId: '778064361074',
    projectId: 'telegram-e5aa0',
    storageBucket: 'telegram-e5aa0.firebasestorage.app',
    iosBundleId: 'com.example.telegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Az0iInDOJ_amEGAaQVHo-tuUCfplbBc',
    appId: '1:778064361074:ios:687cdc2eadcd3edd1eb4eb',
    messagingSenderId: '778064361074',
    projectId: 'telegram-e5aa0',
    storageBucket: 'telegram-e5aa0.firebasestorage.app',
    iosBundleId: 'com.example.telegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4RvmQdusyKNPKWAU_m9GnCdm87kTf4FU',
    appId: '1:778064361074:web:2b3d7bb5fa98648d1eb4eb',
    messagingSenderId: '778064361074',
    projectId: 'telegram-e5aa0',
    authDomain: 'telegram-e5aa0.firebaseapp.com',
    storageBucket: 'telegram-e5aa0.firebasestorage.app',
    measurementId: 'G-SZJE8FPY39',
  );
}
