// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsQseMBFc_psOdvsVlWxmedpK5epX5Xc',
    appId: '1:534905795788:web:93f02d9635cc72bce17e69',
    messagingSenderId: '534905795788',
    projectId: 'project123-a6f34',
    authDomain: 'project123-a6f34.firebaseapp.com',
    storageBucket: 'project123-a6f34.firebasestorage.app',
    measurementId: 'G-KVNE62X7SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhx0lQ3oF2TP8xgU2WdKpQfA7ScAGiQ5I',
    appId: '1:534905795788:android:14c4b3c8c2bd5ce6e17e69',
    messagingSenderId: '534905795788',
    projectId: 'project123-a6f34',
    storageBucket: 'project123-a6f34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0aq86u6L7J9Nobo7t-TMbfdUtjurdp2I',
    appId: '1:534905795788:ios:0ba94808fd6218f1e17e69',
    messagingSenderId: '534905795788',
    projectId: 'project123-a6f34',
    storageBucket: 'project123-a6f34.firebasestorage.app',
    iosBundleId: 'com.example.telegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0aq86u6L7J9Nobo7t-TMbfdUtjurdp2I',
    appId: '1:534905795788:ios:0ba94808fd6218f1e17e69',
    messagingSenderId: '534905795788',
    projectId: 'project123-a6f34',
    storageBucket: 'project123-a6f34.firebasestorage.app',
    iosBundleId: 'com.example.telegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsQseMBFc_psOdvsVlWxmedpK5epX5Xc',
    appId: '1:534905795788:web:8cb25458e0ac1d17e17e69',
    messagingSenderId: '534905795788',
    projectId: 'project123-a6f34',
    authDomain: 'project123-a6f34.firebaseapp.com',
    storageBucket: 'project123-a6f34.firebasestorage.app',
    measurementId: 'G-L1KW88NWVC',
  );
}
